

services:
  postgres:
    image: postgres:15-alpine
    container_name: silklux-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: silklux_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - silklux-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d silklux_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: silklux-app
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/silklux_db
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - silklux-network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:

networks:
  silklux-network:
    driver: bridge
